bar_stadium/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bar_stadium.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('shop.urls')),
)

shop/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('shop.views',
    url(r'^$', 'home'),
    url(r'^boutique/$', 'produits'),
    url(r'^boissons/$', 'boissons'),
    url(r'^glaces/$', 'glaces'),
    url(r'^connexion/$', 'connexion'),
    url(r'^deconnexion/$', 'deconnexion', name='deconnexion'),
    url(r'^service/$', 'gestionService'),
)

bar_stadium/shop/models.py
from django.db import models


class Produit(models.Model):
    nom = models.CharField(max_length=50)
    description = models.TextField()
    prix = models.IntegerField()
    urlImg = models.TextField()


class Boisson(Produit):
    degre = models.IntegerField()
    alcool = models.BooleanField(default=False)


class Glace(Produit):
    parfum = models.CharField(max_length=50)


class Commande(models.Model):
    prixTTC = models.DecimalField(max_digits=6, decimal_places=2)
    prixHT = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    serveur = models.ForeignKey('Serveur')
    loge = models.ForeignKey('Loge')
    produit = models.ManyToManyField(Produit, through='LigneCom')


class LigneCom(models.Model):
    quantite = models.IntegerField()
    produit = models.ForeignKey(Produit)
    commande = models.ForeignKey(Commande)


class Serveur(models.Model):
    class Meta:
        unique_together = (("nom", "prenom"),)
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)


class Loge(models.Model):
    libelle = models.CharField(max_length=50)

bar_stadium/templates/boutique.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<title>La boutique</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="content-language" content="fr" />
<link href="{% static 'style.css' %}"	title="Défaut" rel="stylesheet" type="text/css" media="screen" />
</head>
<body> 

<div id="conteneur"><!-- Conteneur Global --> 
         <div id="header">
		 <!--***** MENU *****-->
              <ul id="menu">
                  <li><a href="{% url 'shop.views.home' %}" title="">Accueil</a></li>
                  {% if user.groups.first.name == "Serveur" %}
                        <li><a href="{% url 'shop.views.gestionService' %}">Gestion Service</a></li>
                  {% elif user.groups.first.name == "Loge" %}
                  		<li id="ici"><a href="{% url 'shop.views.produits' %}" title="">Boutique</a></li> 
                  {% endif %}
              </ul> 	
         </div>
   
         <div id="contenu">
		      <!--***** COLONNE DE GAUCHE *****-->		 
              <div id="left">
		      <!--***** MENU *****-->
                   <div class="hautmenu">Catégories</div><div class="fondmenu">
                        <ul class="menuh">
                            <li><a href="{% url 'shop.views.boissons' %}" title="">Les boissons</a></li> 
                            <li><a href="{% url 'shop.views.glaces' %}" title="">Les glaces</a></li>
                        </ul> 	
                   </div><div class="basmenu"></div>

                   	{% if commandeExistante %}
                   	<div class="hautmenu">Panier</div><div class="fondmenu">
                		<ul class="menuh">
                			{% for ligneCom in commandeExistante.lignecom_set.all %}
                				<li>{{ ligneCom.produit.nom }} (x{{ ligneCom.quantite }})</li>
                			{% endfor %}
                			<form action="." method="post">
									{% csrf_token %}
									<input type="submit" name="validerCommande" value="Valider la commande" />
							</form>
                		</ul>
                   	</div><div class="basmenu"></div><!-- Fin Menu vertical -->
                   	{% endif %}
              </div>
			  
		      <!--***** COLONNE DE DROITE *****-->		
		      <div id="rightBoutique">
			  
 		      <!--***** CADRE NEWS *****-->                
				 <div class="news_haut"></div><div class="news_fond">
				 	{% if location == "boutique" %}
				    	<span class="titre">Nos produits :</span><br />
				    {% elif location == "boissons" %}
				    	<span class="titre">Nos boissons :</span><br />
				    {% elif location == "glaces" %}
				    	<span class="titre">Nos glaces :</span><br />
				    {% endif %}

				      <table>
				     	{% for produit in produits %}
				      	<tr style="margin-bottom:30px;">
				      		<td>
				      			{% if produit.urlImg != "" %}
				      				<img style="float:left;width:100px;margin-right:30px;" src="{{produit.urlImg}}" alt="Image du produit" />
				      			{% else %}
				      				<p>Aucune image</p>
				      			{% endif %}
				      		</td>
				      		<td>
				      			<p style="margin-bottom:10px;"><span class="titre" style="font-size:2em;font-weight: bold;">{{produit.nom}}</span><br/>
				      			Ingredients : 
				      			{% for ingredients in produit.ingredients.all %}
				      				{{ingredients.libelle}} ;
				      			{% endfor %}
				      			</p>
								<p>{{produit.description}}</p>
								<form action="." method="post">
									{% csrf_token %}
									<input type="hidden" name="leProduit" value="{{ produit.pk }}" />
									<input type="number" name="quantite" min="1" value="1">
									<input type="submit" name="addPanier" value="Ajouter au panier" />
								</form>
				      		</td>
				      	</tr>
				      	{% endfor %}
				      </table>

				 </div><div class="news_bas"></div>
				 
				 <!-- Bouton pour remonter en haut de la page -->
                 <!--<div style="text-align: right;margin:0 17px 0 0"><a href="#header"><img src="{% static 'hautdepage.png' %}" alt=""/></a></div>-->
				 
		      </div>
 		      <!--***** PIED *****--> 
              <div id="pied">
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->
                   <div class="copyright">©Design <a href="http://www.kitgraphiquegratuit.org" onclick="window.open(this.href); return false;" title="kits Graphique">Kits Graphiques</a></div>
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->    
              </div>

</div><!-- Fin Contenu -->
</div><!-- Fin Conteneur Global -->
</body>
</html>

bar_stadium/templates/connexion.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<title>Connexion</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="content-language" content="fr" />
<link href="{% static 'style.css' %}"	title="Défaut" rel="stylesheet" type="text/css" media="screen" />
</head>
<body> 

<div id="conteneur"><!-- Conteneur Global --> 
         <div id="header">
		 <!--***** MENU *****-->
              <ul id="menu">
                  <li><a href="{% url 'shop.views.home' %}" title="">Accueil</a></li>
                  {% if user.groups.first.name == "Serveur" %}
                        <li><a href="{% url 'shop.views.gestionService' %}">Gestion Service</a></li>
                  {% elif user.groups.first.name == "Loge" %}
                  		<li><a href="{% url 'shop.views.produits' %}" title="">Boutique</a></li> 
                  {% endif %}
              </ul> 	
         </div>
   
         <div id="contenu">			  
		      <!--***** COLONNE DE DROITE *****-->		
		      <div id="right">
			  
 		      <!--***** CADRE NEWS *****-->                
				 <div class="news_haut"></div><div class="news_fond">
				    <h1>Se connecter</h1>
						{% if error %}
							<p><strong>Utilisateur inexistant ou mauvais de mot de passe.</strong></p>
						{% endif %}

						{% if user.is_authenticated %}
							<p>Vous êtes connecté, {{ user.username }} !<p>
							<a href="{% url 'shop.views.deconnexion' %}">Vous déconnecter ?</a>
						{% else %}
							<form method="post" action=".">
							 	   {% csrf_token %}
							 	   {{ form.as_p }}
							    <input type="submit"/>
							</form>
						{% endif %}
				 </div><div class="news_bas"></div>
				 
				 <!-- Bouton pour remonter en haut de la page -->
                 <!--<div style="text-align: right;margin:0 17px 0 0"><a href="#header"><img src="{% static 'hautdepage.png' %}" alt=""/></a></div>-->
				 
		      </div>
 		      <!--***** PIED *****--> 
             <div id="pied">
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->
                   <div class="copyright">©Design <a href="http://www.kitgraphiquegratuit.org" onclick="window.open(this.href); return false;" title="kits Graphique">Kits Graphiques</a></div>
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->    
              </div>

</div><!-- Fin Contenu -->
</div><!-- Fin Conteneur Global -->
</body>
</html>

bar_stadium/templates/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<title>Accueil</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-language" content="fr" />
<link href="{% static 'style.css' %}"    title="Défaut" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>

<div id="conteneur"><!-- Conteneur Global -->
         <div id="header">
         <!--***** MENU *****-->
              <ul id="menu">
                  <li id="ici"><a href="{% url 'shop.views.home' %}" title="">Accueil</a></li>
                  {% if user.groups.first.name == "Serveur" %}
                        <li><a href="{% url 'shop.views.gestionService' %}">Gestion Service</a></li>
                  {% elif user.groups.first.name == "Loge" %}
                      <li><a href="{% url 'shop.views.produits' %}" title="">Boutique</a></li> 
                  {% endif %}
              </ul>
         </div>

         <div id="contenu">

              <!--***** COLONNE DE DROITE *****-->
              <div id="right">

               <!--***** CADRE PRESENTATION *****-->
                 <div class="news_haut"></div><div class="news_fond">
                      <span class="titre">Bienvenu au Bar-Vip de Stadium-Company</span><br />
                      <p style="margin-top:20px;">
                        Stadium Company est fier de vous accueilir sur notre toute nouvelle platforme de commande. Cette interface vous permet de parcourir notre boutique composé de boissons et de glaces et de passer commande à notre bar en ajoutant simplement des produits à votre panier et en validant votre commande !
                      </p>
                 </div><div class="news_bas"></div>

                 <!-- Bouton pour remonter en haut de la page -->
                 <!--<div style="text-align: right;margin:0 17px 0 0"><a href="#header"><img src="{% static 'hautdepage.png' %}" alt=""/></a></div>-->

              </div>
               <!--***** PIED *****-->
              <div id="pied">
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->
                   <div class="copyright"><a href="{% url 'shop.views.connexion' %}">Connexion</a> | ©Design <a href="http://www.kitgraphiquegratuit.org" onclick="window.open(this.href); return false;" title="kits Graphique">Kits Graphiques</a></div>
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->    
              </div>

</div><!-- Fin Contenu -->
</div><!-- Fin Conteneur Global -->
</body>
</html>

bar_stadium/templates/serveur.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<title>Gestion des commandes</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="content-language" content="fr" />
<meta http-equiv="Refresh" content="10">
<link href="{% static 'style.css' %}"   title="Défaut" rel="stylesheet" type="text/css" media="screen" />
</head>
<body> 

<div id="conteneur"><!-- Conteneur Global --> 
         <div id="header">
         <!--***** MENU *****-->
              <ul id="menu">
                    <li><a href="{% url 'shop.views.home' %}" title="">Accueil</a></li>
                    {% if user.groups.first.name == "Serveur" %}
                        <li  id="ici"><a href="{% url 'shop.views.gestionService' %}">Gestion Service</a></li>
                  {% elif user.groups.first.name == "Loge" %}
                      <li><a href="{% url 'shop.views.produits' %}" title="">Boutique</a></li> 
                  {% endif %}
              </ul>     
         </div>
   
         <div id="contenu">
              
              <!--***** COLONNE DE DROITE *****-->      
              <div id="right">
              
              <!--***** CADRE NEWS *****-->                
                 <div class="news_haut"></div><div class="news_fond">
                      {% if commandes %}
                          <span class="titre">Les commandes :</span><br />
                          <table>
                                {% for commande in commandes %}
                                    {% if commande.validee == True %}
                                    <tr style="margin-bottom:30px;">
                                        <td style="background-color:Green">
                                            <p>Commande à livrer pour la loge : {{ commande.loge.libelle }}</p>
                                            <p>SERVEUR ATTRIBUE : {{ commande.serveur.nom }} {{ commande.serveur.prenom }}</p>
                                            <p>Produit(s) :<br/>
                                                <ul>
                                                    {% for ligneCom in commande.lignecom_set.all %}
                                                        <li>Quantité : {{ ligneCom.quantite }}</li>
                                                        <li>{{ ligneCom.produit.nom }}</li>
                                                            <ul>
                                                                {% for ingredients in ligneCom.produit.ingredients.all %}
                                                                    <li>{{ ingredients.libelle }}</li>
                                                                {% endfor %}
                                                            </ul>
                                                    {% endfor %}
                                                </ul>
                                            </p>
                                            <form action="." method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="laCommande" value="{{ commande.pk }}" />
                                                <input type="submit" name="commandeServie" value="Commande servie" />
                                            </form>
                                        </td>
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                                {% for commande in commandes %}
                                    {% if commande.validee == False %}
                                    <tr style="margin-bottom:30px;">
                                        <td style="background-color:blue;">
                                            <p>Commande en préparation pour la loge : {{ commande.loge.libelle }}</p>
                                            <p>SERVEUR ATTRIBUE : {{ commande.serveur.nom }} {{ commande.serveur.prenom }}</p>
                                            <p>Produit(s) :<br/>
                                            <ul>
                                                {% for ligneCom in commande.lignecom_set.all %}
                                                        <li>Quantité : {{ ligneCom.quantite }}</li>
                                                        <li>{{ ligneCom.produit.nom }}</li>
                                                            <ul>
                                                                {% for ingredients in ligneCom.produit.ingredients.all %}
                                                                    <li>{{ ingredients.libelle }}</li>
                                                                {% endfor %}
                                                            </ul>
                                                {% endfor %}
                                            </ul>
                                            </p>
                                        </td>
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                            </table>
                        {% else %}
                            <span class="titre">Aucune commande en cours..</span><br />
                        {% endif %}
                      

                 </div><div class="news_bas"></div>
                 
                 <!-- Bouton pour remonter en haut de la page -->
                 <!--<div style="text-align: right;margin:0 17px 0 0"><a href="#header"><img src="{% static 'hautdepage.png' %}" alt=""/></a></div>-->
                 
              </div>
              <!--***** PIED *****--> 
              <div id="pied">
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->
                   <div class="copyright">©Design <a href="http://www.kitgraphiquegratuit.org" onclick="window.open(this.href); return false;" title="kits Graphique">Kits Graphiques</a></div>
                   <!-- mention de copyright Ne pas retirer sans autorisation écrite -->    
              </div>

</div><!-- Fin Contenu -->
</div><!-- Fin Conteneur Global -->
</body>
</html>